### ISSUE TITLE
Ataseaza shema de la baza de date

### ISSUE THREAD

**Issue by bovidiu** [alexchirea/banca#1]

**Comment by alexchirea** [comment]
Nu cred ca o mai am...

**Comment by bovidiu** [comment]
Ok, imi va fi cam greu sa vad daca o sa si functioneze dar idea este sa vezi un model de design pattern :)

**Comment by alexchirea** [comment]
Acum o incarc :)

**Comment by alexchirea** [comment]
https://github.com/alexchirea/banca/blob/master/db.sql
